BlockUtils: Fix epoch day calculation
Simplifies the code to avoid using daysBetween to calculate the epoch
days.

Also adds a test to prevent regressions in the future.

Test failure without the fix:
[ERROR] Failures:
[ERROR]   BlockUtilsTest.fieldToString:157 expected:<...], col3=[18339, 1825[9]]}> but was:<...], col3=[18339, 1825[8]]}>

The epoch days is off by 1 without the fix.

Credits go to @akuzin1 for testing and pinpointing where this problem
was occurring.